### ISSUE TITLE
BUG: MathMod-11.0 quits (crashes) as soon as it is started on Windows

### ISSUE THREAD

**Issue by Markospoko** [parisolab/mathmod#185]
All I can see are gray windows for a second. It runs on Linux but in about it's MathMod-10.1.
edit: app's windows have gray background and they are shown until "Application stopped" finishes.

**Comment by parisolab** [comment]
Hi, 
What windows version are you using Windows (10/8/7) ?
In Linux, which distros of Linux do you have?
Also, under Linux, it's really easy (and better) to compile MathMod from source :

1) sudo apt-get update -y
2) sudo apt-get install -y qt5-default
then go to the source code directory and type:
3) qmake; make

**Comment by Markospoko** [comment]
Windows 7 64-bit

**Comment by parisolab** [comment]
I was told on a youtube video comment that MathMod was crashing with this configuration "windows 7 64bit i3 8gb 4010U CPU" . Is it the same MathMod user?

**Comment by Markospoko** [comment]
No, if you are asking if I'm that user, I'm not, I messaged you on fb but I shared some more here.
I use Manjaro if you are so interested what Lin I use also, I compiled MMod but it shows 10.1, maybe it's only text.

**Comment by parisolab** [comment]
Have you tried the MathMod-11.0 32Bit for windows? It's available from : https://github.com/parisolab/mathmod/releases/tag/11.0
For Linux, MathMod was tested and works fine with the latest Manjaro (for RaspberryPi) . The latest code is available from https://github.com/parisolab/mathmod  ( MathMod showed version:"11.1  (development version)" ) and I strongly recommend to test it since it has already some minor corrections over the 11.0 version.

![Screen Shot 2021-03-30 at 7 42 18 AM](https://user-images.githubusercontent.com/38238160/113058933-cdd20f00-917c-11eb-84b1-c65a627e2326.png)

**Comment by Markospoko** [comment]
32bit is ok, I'll be awaiting 11.1.
